 language: node_js
 node_js:
   - "0.10"
   - "0.8"
   - "0.7"
 before_script:
  - npm install -g grunt-cli
 before_install:
 - sudo npm cache clear; sudo apt-get update && sudo apt-get install -y redis-server
